name: hilltone_school
description: A Flutter multi-role android app for students and teachers.


environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  http: ^1.4.0
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  image_picker: ^1.1.2
  url_launcher: ^6.3.1
  syncfusion_flutter_pdfviewer: ^29.2.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/logo.png
    - assets/syllabus.pdf
